SET SERVEROUTPUT ON 
DECLARE
    vPi CONSTANT NUMBER(38,15) := 3.1415;

BEGIN 
    DBMS_OUTPUT.PUT_LINE('Pi= '||vpi);
END;    


SET SERVEROUTPUT ON
DECLARE
    vNome CONSTANT VARCHAR(200) := 'Murilo';
BEGIN
    DBMS_OUTPUT.PUT_LINE('OLÁ ' || vNome);
END;        

